const ServicesActionTypes = {
	FETCH_SERVICES_SUCCESS: 'services/FETCH_SERVICES_SUCCESS',
	FETCH_SERVICES_FAILED: 'services/FETCH_SERVICES_FAILED',
	FETCH_SERVICES_PENDING: "services/FETCH_SERVICES_PENDING",
	FILTER_SERVICES_ITEMS_BY_CATEGORY: 'services/FILTER_SERVICES_ITEMS_BY_CATEGORY',
	SEARCH_SERVICES_QUERY: 'services/SEARCH_SERVICES_QUERY',
	GET_SERVICE_MIN_MAX_VALUE: 'services/GET_SERVICE_MIN_MAX_VALUE'
}

export default ServicesActionTypes;