const OrdersActionTypes = {
	ADD_NEW_ORDER_SUCCESS: 'order/ADD_NEW_ORDER_SUCCESS',
	ORDERS_STATUS_PENDING: 'order/ADD_NEW_ORDER_PENDING',
	ADD_NEW_ORDER_FAILED: 'order/ADD_NEW_ORDER_FAILED',
	FETCH_ALL_ORDERS_SUCCESS: 'order/FETCH_ALL_ORDERS_SUCCESS',
	FETCH_ALL_ORDERS_FAILED: 'order/FETCH_ALL_ORDERS_FAILED',
	FILTER_ORDERS_BY_SERVICE_CATEGORY: 'order/FILTER_ORDERS_BY_SERVICE_CATEGORY',
	SEARCH_ORDERS_BY_SERVICE: 'order/SEARCH_ORDERS_BY_SERVICE'
};

export default OrdersActionTypes;